### ISSUE TITLE
Add possibility to pass version

### ISSUE THREAD

**Issue by yhesse** [DArtagan/docker-spigot#2]
It would be nice to be able to change the version. For example, now that 1.12 is released, they (spigot) are working on a stable updated version. It's not yet the default one that is compatible but you can already run it when you manually change the version to 1.12.

**Comment by DArtagan** [comment]
That's beyond the work I want to do for this Dockerfile.  Docker images are like snapshots in time, when the image is first created, all programs are frozen at that point.  Containers are instances of images.  It is possible to have container where the spigot build tools run every time the container was started and then you could pass in a version and it would be built live.  I prefer to have spigot built before the container's even started, and thus I'll be sticking with the frozen, default version of spigot that was built when the image was made.

Here's a suggestion though:
Once your container is up, ``docker exec`` these commands manually:
```
java -jar /minecraft_build/BuildTools.jar --rev 1.12
apk del build-dependencies
mv /minecraft_build/spigot-*.jar /minecraft/spigot.jar
rm -r /minecraft_build
```
(and then you might need to restart your docker container, I'm not sure)

**Comment by yhesse** [comment]
Thanks for that, I got this working but there is a bug. I could not build at first because there was no git installed. You should add git in your dockerfile.

**Comment by DArtagan** [comment]
Hey! I'm glad to hear that you got it - good detective work.  Git is intentionally not included, because this image aims to be as small and light as possible.  Looking in the [Dockerfile](https://github.com/DArtagan/docker-spigot/blob/master/Dockerfile), you can see that it's installed as a build-dependency during the build process but then removed immediately after.  Sorry to use the old line: "it's not a bug, it's a feature".

**Comment by yhesse** [comment]
ah ok :) Well, everything is working so thanks!
